spring:
  application:
    name: TaskManager
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

db:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/taskmgr

jwt:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
  ttl: 15