CREATE TABLE IF NOT EXISTS event(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS users(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    TEXT NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    admin       BIT NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS attendance(
    user_id     INT REFERENCES users(id),
    event_id    INT REFERENCES event(id),

    PRIMARY KEY(user_id, event_id)
);